### ISSUE TITLE
wrong library name

### ISSUE THREAD

**Issue by GuLinux** [qhyccd-lzr/QHYCCD_Linux#10]
Hi again. This is a very small issue, I think: the "internal" library name in version 0.1.6 is still 0.1.5.
When I link to the libqhy_64.bin file, the link is resolved as libqhy.so.0.1.5.

**Comment by qhyccd-lzr** [comment]
Hello
thanks.fixed again.
please do not hesitate to report any bugs.I am glad to hear from you.
