### ISSUE TITLE
libpng static link

### ISSUE THREAD

**Issue by GuLinux** [qhyccd-lzr/QHYCCD_Linux#12]
Hello, I'm having a little problem with my Qt application.
When I compile, I link against Qt, which is linked to my system libpng (archlinux, 1.6.16).
However, I receive this warning when running it:
libpng warning: Application built with libpng-1.6.16 but running with 1.5.12

It seems that this is a static lib embedded in libqhy (I can see it running "strings" command on it).
It is possible to ship libqhy without this static library? The most visible issue, beside this warning, is that in my application I cannot load anymore png pixmaps.
Thanks
Marco

**Comment by trlsmax** [comment]
same here when I link it with PHD2

**Comment by qhyccd-lzr** [comment]
removed already.
