### ISSUE TITLE
Color pattern examples and/or documentation

### ISSUE THREAD

**Issue by GuLinux** [qhyccd-lzr/QHYCCD_Linux#15]
Hello,
I would like to implement color support on my capture software, but the QHYCCD API lacks a bit of information about colour images.
GetQHYCCDLiveFrame does return bpp and channels, but there is no info about the colour pattern. Is it a bayer pattern (like RGGB) to be interpolated, or a triplet for each pixel (RGB)?
I also saw a BAYER_ID struct, but it seems to be unused.

Thanks
Marco

**Comment by qhyccd-lzr** [comment]
Hi
bayer pattern is used at the laster version.
