### ISSUE TITLE
Don't use static libraries

### ISSUE THREAD

**Issue by GuLinux** [qhyccd-lzr/QHYCCD_Linux#17]
Hello again, this is mostly a derivative of issue #12 , but since it seems to be more widespread than I thought, I think it's best to open a new issue.
In fact, not only libpng, but also libjpeg, and more importantly, OpenCV, are linked statically inside libqhy.
This forbids users to use that all that libraries on an application, because when I link to my system opencv library, qhy driver just stops working. I just wanted to switch my application from imagemagick to opencv, but this way I cannot use qhy driver.
Please fix this as soon as possible.
Thanks
Marco

**Comment by GuLinux** [comment]
Please, can we have news about this bug, and more generally about this driver?
It's been all silent since half a year!

**Comment by goodwink** [comment]
This is a major impact to me also.  I cannot support QHY cameras in my application until this is resolved since I use opencv.

**Comment by qhyccd-lzr** [comment]
okay.opencv is removed.
