### ISSUE TITLE
CMakeLists.txt has incorrect quotes

### ISSUE THREAD

**Issue by historicbruno** [qhyccd-lzr/QHYCCD_Linux#19]
When I tried to build the SDK on Arch Linux ARM, the driver filename was invalid because LIBQHY_VERSION is defined with incorrect quotes:
`set(LIBQHY_VERSION “0.1.7”)`
should be:
`set(LIBQHY_VERSION "0.1.7")`

**Comment by qhyccd-lzr** [comment]
is there any difference between the two strings you are typing?

**Comment by historicbruno** [comment]
Hi, yes. The first incorrect quote has **U+201C : LEFT DOUBLE QUOTATION MARK {double turned comma quotation mark}** and **U+201D : RIGHT DOUBLE QUOTATION MARK {double comma quotation mark}**, but it should be **U+0022 : QUOTATION MARK**.

**Comment by qhyccd-lzr** [comment]
okay.thanks a lot.
