### ISSUE TITLE
armv7 workaround obsolete?

### ISSUE THREAD

**Issue by historicbruno** [qhyccd-lzr/QHYCCD_Linux#20]
In CMakeLists.txt, there is a note and a workaround for armv7 systems:
```
ELSEIF(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "armv7l")
 #JM 2015-04-10: Use armv6 for now until armv7 version is fixed by QHY
  exec_program(cp ARGS ${CMAKE_CURRENT_SOURCE_DIR}/libqhy_arm_v6.bin ${CMAKE_BINARY_DIR}/libqhy.so.${LIBQHY_VERSION})
```

I notice the drivers have been updated since then, so I tested this on a Raspberry Pi 2 (armv7) by removing the workaround and using `libqhy_arm_v7.bin` instead. Am I missing the problem or is the workaround obsolete?

**Comment by qhyccd-lzr** [comment]
okay.thanks.I have fixed.
