### ISSUE TITLE
QHY5L||| and QHY224COOL support?

### ISSUE THREAD

**Issue by goodwink** [qhyccd-lzr/QHYCCD_Linux#24]
Will these cameras be added to this ADK's support list?

**Comment by 0ctane** [comment]
Here is some data for the QHY5III-185C
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.4.9-v7+ #884 SMP Fri May 6 17:28:59 BST 2016 armv7l GNU/Linux

pi@raspberrypi:~ $ dmesg | tail -6
[  688.379143] usb 1-1.3: new high-speed USB device number 4 using dwc_otg
[  688.479999] usb 1-1.3: New USB device found, idVendor=1618, idProduct=0185
[  688.480020] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  688.480032] usb 1-1.3: Product: WestBridge 
[  688.480044] usb 1-1.3: Manufacturer: Cypress
[  688.480056] usb 1-1.3: SerialNumber: 0000000004BE

pi@raspberrypi:~ $ lsusb
Bus 001 Device 004: ID 1618:0185

**Comment by qhyccd-lzr** [comment]
yes.QHY5III series already support.
