### ISSUE TITLE
Unable to load firmware on QHYIII290

### ISSUE THREAD

**Issue by GuLinux** [qhyccd-lzr/QHYCCD_Linux#29]
Hello,
I just noticed 2 issues with the udev rule/firmware loading on the QHYIII290:

firstly, the udev rule line is missing from 85-qhy.rules:
```
ATTRS{idVendor}=="1618", ATTRS{idProduct}=="0290", RUN+="/sbin/fxload -t fx2 -I /lib/firmware/qhy/QHY5III290.img -D $env{DEVNAME}"
```
When I tried adding this line to my udev rule file, I then received a second error regarding firmware loading:
```
May 10 21:49:34 bluebox systemd-udevd[10908]: starting '/sbin/fxload -t fx2 -I /lib/firmware/qhy/QHY5III290.img -D /dev/bus/usb/001/014'
May 10 21:49:34 bluebox systemd-udevd[10895]: '/sbin/fxload -t fx2 -I /lib/firmware/qhy/QHY5III290.img -D /dev/bus/usb/001/014'(err) 'can't modify CPUCS: Broken pipe'
May 10 21:49:34 bluebox systemd-udevd[10895]: Process '/sbin/fxload -t fx2 -I /lib/firmware/qhy/QHY5III290.img -D /dev/bus/usb/001/014' failed with exit code 255.
```

My OS is Arch Linux.
Thanks,
Marco

**Comment by GuLinux** [comment]
More info on this issue:
I looked at the 85-qhy.rules file in libqhy from INDI, and it's totally different.
It also mentions a "fx3" firmware type, which is not supported by the legacy fxload (found in ubuntu 16.04, for instance), but it's supported by the libusb version.

After using this command instead, I was able to load the firmware

**Comment by qhyccd-lzr** [comment]
Hello Marco,


       It should be the FX3 support issue on the fx2load. Please look at this  http://note.youdao.com/groupshare/?token=E748793177414A58A64936699B42BC8B&gid=7195236 
  


Best regards,
Qiu Hongyun

2017-05-11 



Dr,Qiu Hongyun 



发件人： Marco Gulino 
发送时间： 2017-05-11  04:53:56 
收件人： qhyccd-lzr/QHYCCD_Linux 
抄送： Subscribed 
主题： [qhyccd-lzr/QHYCCD_Linux] Unable to load firmware on QHYIII290 (#29) 
 
Hello,
I just noticed 2 issues with the udev rule/firmware loading on the QHYIII290:
firstly, the udev rule line is missing from 85-qhy.rules:
ATTRS{idVendor}=="1618", ATTRS{idProduct}=="0290", RUN+="/sbin/fxload -t fx2 -I /lib/firmware/qhy/QHY5III290.img -D $env{DEVNAME}"

When I tried adding this line to my udev rule file, I then received a second error regarding firmware loading:

**Comment by GuLinux** [comment]
Thanks.
I´m working with INDI ppa maintainer to add another fxload version for usb3 cameras.
