### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by GuLinux** [qhyccd-lzr/QHYCCD_Linux#9]
There have been a few updates, but no examples yet back.
Could you please update the code?
Thanks
Marco

**Comment by qhyccd-lzr** [comment]
yes.I am doing that.please keep update.

**Comment by GuLinux** [comment]
Thank you, it quite helped to better understand some things (I'm looking particularly to the Live example).
There is something a bit wrong, however: the frame rate is way too hight (18836 fps).
Also it's not very clear if the int parameters in GetQHYCCDLiveFrame are input or output parameters: they're pointers, so my guess is that they're output, but they're always kept to 0 in my own example.

Perhaps the live frame is not available yet on each call? This would explain both why the frame rate is so high, and why the output parameters are set to 0.
Maybe one should also check for GetQHYCCDExposureRemaining or GetQHYCCDReadingProgress? How are these API used? GetQHYCCDExposureRemaining is not very clear.
Thanks again!
Marco

**Comment by qhyccd-lzr** [comment]
Hello 
please try the 0.1.6 version.forgive me.I forget to update.
okay.I will continue to write sample for those apis.
thanks for your report.

**Comment by GuLinux** [comment]
Thank you, It's starting to work as expected :)
I'm trying to build a Qt application a bit like ezplanetary, maybe I'll keep bugging you for more advices.
Maybe you want also to take a look?
Thanks
Marco
